##### Ad-hoc conda apptainer #####


containerized: "docker://durr1602/gyoza:latest"


##### Load rules #####


include: "rules/common.smk"
include: "rules/cutadapt.smk"
include: "rules/pandaseq.smk"
include: "rules/vsearch.smk"
include: "rules/stats.smk"
include: "rules/pool_stats.smk"
include: "rules/parse_fasta.smk"
include: "rules/process_read_counts.smk"


if config["qc"]["perform"]:
    include: "rules/qc.smk"

if config["report"]["generate"]:
    include: "rules/report.smk"

design = config["design"]
if design == "random":
    include: "rules/annotate_random.smk"
elif design == "provided":
    include: "rules/compare.smk"
    include: "rules/annotate_mutants.smk"
elif design == "codon":
    include: "rules/generate_expected_mutants.smk"
    include: "rules/compare.smk"
    include: "rules/annotate_mutants.smk"
else:
    raise ValueError(f"Unknown experiment design: {design}")


##### Target(s) #####


rule all:
    input:
        get_target(),