# Main configuration file for gyōza

reads:
    # Specify path to directory containing sequencing data
    path: 'config/reads/'

samples:
    # Specify path to sample layout
    path: 'config/project_files/layout.csv'
    # Choice of samples to process, either list of Sample_names: ['My_sample_1', 'My_sample_2']
    # or to process all samples: 'all'
    selection: 'all'
    # Specify what makes each sample unique (other than Timepoint and Replicate)
    attributes: ['Species', 'Mating_type', 'Fragment']
    # Specify path to create file containing the number of mitotic generations for each condition
    generations: 'config/project_files/nbgen.csv'
    # Specify path to file containing the wild-type DNA sequences
    wt: 'config/project_files/wt_seq.csv'
    # Specify path to create file (if needed) containing all expected mutated sequences
    # For barcoded-design experiments, this corresponds to the dataframe associating barcodes with mutants
    expected_mut: 'config/project_files/expected_mutants.csv'
    
codon:
    # Codon table
    table: 'config/project_files/ScerevisiaeTAXID559292_Cocoputs_codon_table.csv'
    # Codon mode, currently supports "NNN", "NNK", "NNN x NNN" or "NNK x NNK"
    mode: 'NNN'

barcode:
    # Level to which read count is attributed (default: 'nt_seq', change to 'barcode' for barcoded design)
    rc_level: 'nt_seq'
    # Specify barcode attributes to label each variant
    attributes: []

rc_aims:
    # Specify targeted read count per sample in scientific notation
    exp_rc_per_sample: 3e4
    # Specify target read count per variant (integer)
    exp_rc_per_var: 5

filter:
    # Specify read count threshold (integer) to label variants with a confidence score
    rc_threshold: 10

qc:
    # Set to True if you want to run FASTQC on all raw FASTQ files and generate a MultiQC report
    perform: True

normalize:
    # Set to True if you want to normalize impact scores with the number of cellular generations
    with_gen: False
    
report:
    # Set to True if you want the HTML report to be automatically generated upon full completion of the workflow
    generate: True

plots:
    # Indicate in which format(s) you want to export plots: ['png','pdf']
    # Plots will be exported in .svg regardless of what is specified below
    format: ['png']