# Main configuration file for gyōza

project:
    # Specify the design of your experiment: codon | provided | barcode | random
    # codon: Automatically generate all expected mutants based on the codon mode
    # provided: You provide the list of expected mutants
    # barcode: You provide the dataframe of barcode-variant associations
    # random: Random mutagenesis - mutants observed in the sequencing data are directly annotated
    design: 'codon'
    # Specify path to folder containing project-specific files
    folder: 'config/project_files/'
    # Specify what makes each sample unique (other than Timepoint and Replicate)
    sample_attributes: ['Species', 'Mating_type', 'Fragment']

reads:
    # Specify if reads are paired-end (True) or single-end (False)
    paired: True
    # Specify path to directory containing sequencing data
    path: 'config/reads/'
    # Specify targeted read count per sample in scientific notation
    exp_rc_per_sample: 3e4
    # Specify read count threshold (integer) to label variants with a confidence score
    rc_threshold: 10

barcode:
    # For 'barcode' designs only
    # Specify barcode attributes to label each variant, e.g. ['bc_index'] (default: [])
    attributes: []

random:
    # For 'random' designs only
    # Acceptable number of amino acid changes relative to wild-type
    Nham_aa_max: 1

perform_qc: True
    # Set to True if you want to run Fastp on all raw FASTQ files and generate a MultiQC report

process_read_counts: True
    # Set to True if you want to convert read counts into functional impact scores

normalize_with_gen: False
    # Set to True if you want to normalize impact scores with the number of cellular generations

plot_formats: ['png']
    # Indicate in which format(s) you want to export plots, e.g. ['png','pdf'] (most formats supported)
    # Plots will be exported in .svg regardless of what is specified