$schema: "https://json-schema.org/draft/2020-12/schema"

description: main configuration file

type: object

properties:

  project:
    type: object
    properties:
      design:
        type: string
        description: "Design of your experiment: codon | provided | barcode | random"
        enum: ['codon', 'provided', 'barcode', 'random']
        default: 'random'
      folder:
        type: string
        description: Path to project folder (should end with '/' or '\')
        pattern: '^[\\\/\-\_\.A-Za-z0-9]+(\\|\/){1}$'
      sample_attributes:
        type: array
        description: List of sample attributes = columns in the sample layout other than Timepoint and Replicate
        uniqueItems: true
        default: []
        items:
          type: string
    required:
      - design
      - folder
      - sample_attributes

  reads:
    type: object
    properties:
      paired:
        type: boolean
        description: Specify if reads are paired-end (True) or single-end (False)
        default: True
      path:
        type: string
        description: Path to reads folder (should end with '/' or '\')
        pattern: '^[\\\/\-\_\.A-Za-z0-9]+(\\|\/){1}$'
      exp_rc_per_sample:
        type: string
        description: Expected read count per sample in scientific notation without quotes, e.g. 3e2
        pattern: -?\d\.?\d*[Ee][+\-]?\d+
      rc_threshold:
        type: integer
        description: Read count threshold (integer). Used to label variants based on the read count at T0
        default: 10
    required:
      - paired
      - path
      - exp_rc_per_sample
      - rc_threshold

  barcode:
    type: object
    properties:
      attributes:
        type: array
        description: List of barcode attributes
        uniqueItems: true
        default: []
        items:
          type: string
    required:
      - attributes

  random:
    type: object
    properties:
      Nham_aa_max:
        type: integer
        description: Acceptable number of amino acid changes relative to wild-type (used to filter variants of 'random' designs)
        minimum: 1
        default: 1
    required:
      - Nham_aa_max

  perform_qc:
    type: boolean
    description: Set to True to run FASTQC and MultiQC
    default: False

  process_read_counts:
    type: boolean
    description: Set to True if you want to convert read counts into functional impact scores
    default: False

  normalize_with_gen:
    type: boolean
    description: Set to True to normalize impact scores with the number of cellular generations
    default: False

  plot_formats:
    type: array
    description: Format of plots for export, list of extensions, e.g. ['png','pdf']
    uniqueItems: true
    default: ['png']
    items:
      type: string
      enum: ['eps', 'jpg', 'jpeg', 'pdf', 'pgf', 'png', 'ps', 'raw', 'rgba', 'svg', 'svgz', 'tif', 'tiff']

required:
  - project
  - reads
  - barcode
  - random
  - perform_qc
  - process_read_counts
  - normalize_with_gen
  - plot_formats
