name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:

  Linting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Lint workflow
      uses: snakemake/snakemake-github-action@v1.25.1
      with:
        directory: .
        snakefile: workflow/Snakefile
        args: "--lint"

  Testing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        paired: [true, false]
    
    steps:
      - uses: actions/checkout@v4
      - name: Test workflow (${{ matrix.paired && 'paired-end' || 'single-end' }})
        uses: snakemake/snakemake-github-action@v2.0.3
        with:
          task: run
          stagein: |
            mkdir -p .test
            # Create symbolic mirror of project root inside .test
            ln -snf ../config .test/config
            ln -snf ../workflow .test/workflow
            
            # Handle the conditional flag for single-end mode
            if [ "${{ matrix.paired }}" = "false" ]; then
              export ADD_FLAG="--until stats"
            else
              export ADD_FLAG=""
            fi
          args: >-
            --directory .test
            --snakefile workflow/Snakefile
            --config reads:paired=${{ matrix.paired }}
            --cores 3
            --use-conda
            --show-failed-logs
            $ADD_FLAG
